### ISSUE TITLE
Issue with saving license with "format" option

### ISSUE THREAD

**Issue by kedarpanse** [verhas/License3jRepl#1]
When trying to save license in specific format, the cmd line argument is not parsed properly resulting in to bad license file.  I think cmd line parser parses the argument without worrying about format option.

Snippet:

L3j> $ saveLicense format=BINARY myLicense.bin
License w/o owner is in memory.
Public key in memory.
Private key in memory.
[INFO] License was saved into the file C:\Users\Temp\format=BINARY myLicense.bin

L3j> $ ll myLicense.bin
[ERROR] Feature string representation needs '=' after the type

**Comment by verhas** [comment]
Contrary what it seems this is a minor issue. The argument is parsed properly and the file is generated. It can also be loaded. The bug is cosmetic:

The name of the file contains the parameters when (`format=BINARY`) only when printed to the screen as a message. If you look at the file `myLicense.bin` in the directory it is there.

When you try to load the license it gives you an error message and this is absolutely correct. You saved the license file as `BINARY` but you try to load it as `TEXT` (default format). It can not be done. You have to use the command line:

`ll format=BINARY myLicense.bin`
