### ISSUE TITLE
Missing Class

### ISSUE THREAD

**Issue by Reggraham** [verhas/License3jRepl#8]
I had to update my Java in order to get it to recognise the class files but I now get the below.
I have tried to load the source(EclipseIDE) but I get numerous errors of the same type Set.of is undefined and final var cannot resolve to type with options of change project compliance settings to 10, create class var, change feature(javax.license3j)

MacBook-Pro:bin reg$ java -jar ~/Scripts/License3jrepl-3.1.5.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javax0/repl/Repl
	at javax0.license3jrepl.App.<init>(App.java:54)
	at javax0.license3jrepl.App.main(App.java:149)
Caused by: java.lang.ClassNotFoundException: javax0.repl.Repl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more

**Comment by verhas** [comment]
Upgrading Java is always a good pracice. I also recommend to have all therecent versions. I personally have Java 8, 9, 10, 11, 13 and 14 currently on my machine and I have

```
use_java_10
use_java_11
use_java_13
use_java_14
use_java_9
```

bash scripts the help to switch between the different versions. The content of the shell script `use_java_9` is, for example:

```
#! /bin/bash
export JAVA_HOME=$(/usr/libexec/java_home -v 9)
```

It is important to start it using the command line

```
. ~/user_java_9
```
I assume that you use at least Java 13 at the moment, or else the reply cannot be started. That was the latest Java release when License3Repl 3.1.5 was released. You can easily check it using `java -version`.

The exception you get is caused by the fact that you start the wrong JAR file. When the build process for Licese3repl runs there are two JAR files created. One contains the classes of the program but does not contain the library classes. You can use this class to start the application but in this case, you have to specify the other JAR files that contain the code for the used libraries.

To avoid searching for and copying these files there is another JAR that has all the needed classes packed together. It is named `License3jrepl-3.1.5-jar-with-dependencies.jar`. Thus your command line has to be

```
MacBook-Pro:bin reg$ java -jar ~/Scripts/License3jrepl-3.1.5-jar-with-dependencies.jar
```
